# Generated by Django 3.1.8 on 2021-11-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthwealth', '0002_auto_20211123_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Secured Health Document'},
        ),
    ]
