# Generated by Django 3.1.8 on 2021-11-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwealth', '0003_auto_20211123_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('1', 'Lab result'), ('2', 'Health recipe'), ('3', 'Health certificate')], max_length=50, null=True),
        ),
    ]
